export const BANNER_CREATE = "BANNER_CREATE";
export const BANNER_CREATE_SUCCESS = "BANNER_CREATE_SUCCESS";
export const BANNER_CREATE_FAILURE = "BANNER_CREATE_FAILURE";
export const SHOW_LOADING_BANNER_CREATE = "SHOW_LOADING_BANNER_CREATE";

export const BANNER_LIST = "BANNER_LIST";
export const BANNER_LIST_SUCCESS = "BANNER_LIST_SUCCESS";
export const BANNER_LIST_FAILURE = "BANNER_LIST_FAILURE";
export const SHOW_LOADING_BANNER_LIST = "SHOW_LOADING_BANNER_LIST";

export const BANNER_DELETE = "BANNER_DELETE";
export const BANNER_DELETE_SUCCESS = "BANNER_DELETE_SUCCESS";
export const BANNER_DELETE_FAILURE = "BANNER_DELETE_FAILURE";
export const SHOW_LOADING_BANNER_DELETE = "SHOW_LOADING_BANNER_DELETE";

export const BANNER_UPDATE = "BANNER_UPDATE";
export const BANNER_UPDATE_SUCCESS = "BANNER_UPDATE_SUCCESS";
export const BANNER_UPDATE_FAILURE = "BANNER_UPDATE_FAILURE";
export const SHOW_LOADING_BANNER_UPDATE = "SHOW_LOADING_BANNER_UPDATE";
