export const CATEGORY_CREATE = "CATEGORY_CREATE";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAILURE = "CATEGORY_CREATE_FAILURE";
export const SHOW_LOADING_CATEGORY_CREATE = "SHOW_LOADING_CATEGORY_CREATE";

export const CATEGORY_LIST = "CATEGORY_LIST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAILURE = "CATEGORY_LIST_FAILURE";
export const SHOW_LOADING_CATEGORY_LIST = "SHOW_LOADING_CATEGORY_LIST";

export const CATEGORY_UPDATE = "CATEGORY_UPDATE";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAILURE = "CATEGORY_UPDATE_FAILURE";
export const SHOW_LOADING_CATEGORY_UPDATE = "SHOW_LOADING_CATEGORY_UPDATE";
