export const PHOTOGALLERY_CREATE = "PHOTOGALLERY_CREATE";
export const PHOTOGALLERY_CREATE_SUCCESS = "PHOTOGALLERY_CREATE_SUCCESS";
export const PHOTOGALLERY_CREATE_FAILURE = "PHOTOGALLERY_CREATE_FAILURE";
export const SHOW_LOADING_PHOTOGALLERY_CREATE = "SHOW_LOADING_PHOTOGALLERY_CREATE";

export const PHOTOGALLERY_LIST = "PHOTOGALLERY_LIST";
export const PHOTOGALLERY_LIST_SUCCESS = "PHOTOGALLERY_LIST_SUCCESS";
export const PHOTOGALLERY_LIST_FAILURE = "PHOTOGALLERY_LIST_FAILURE";
export const SHOW_LOADING_PHOTOGALLERY_LIST = "SHOW_LOADING_PHOTOGALLERY_LIST";

export const PHOTOGALLERY_DELETE = "PHOTOGALLERY_DELETE";
export const PHOTOGALLERY_DELETE_SUCCESS = "PHOTOGALLERY_DELETE_SUCCESS";
export const PHOTOGALLERY_DELETE_FAILURE = "PHOTOGALLERY_DELETE_FAILURE";
export const SHOW_LOADING_PHOTOGALLERY_DELETE = "SHOW_LOADING_PHOTOGALLERY_DELETE";
