export const POST_CREATE = "POST_CREATE";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";
export const SHOW_LOADING_POST_CREATE = "SHOW_LOADING_POST_CREATE";

export const POST_LIST = "POST_LIST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAILURE = "POST_LIST_FAILURE";
export const SHOW_LOADING_POST_LIST = "SHOW_LOADING_POST_LIST";

export const POST_DELETE = "POST_DELETE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";
export const SHOW_LOADING_POST_DELETE = "SHOW_LOADING_POST_DELETE";


export const POST_UPDATE = "POST_UPDATE";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAILURE = "POST_UPDATE_FAILURE";
export const SHOW_LOADING_POST_UPDATE = "SHOW_LOADING_POST_UPDATE";