export const VIDEOGALLERY_CREATE = "VIDEOGALLERY_CREATE";
export const VIDEOGALLERY_CREATE_SUCCESS = "VIDEOGALLERY_CREATE_SUCCESS";
export const VIDEOGALLERY_CREATE_FAILURE = "VIDEOGALLERY_CREATE_FAILURE";
export const SHOW_LOADING_VIDEOGALLERY_CREATE = "SHOW_LOADING_VIDEOGALLERY_CREATE";

export const VIDEOGALLERY_LIST = "VIDEOGALLERY_LIST";
export const VIDEOGALLERY_LIST_SUCCESS = "VIDEOGALLERY_LIST_SUCCESS";
export const VIDEOGALLERY_LIST_FAILURE = "VIDEOGALLERY_LIST_FAILURE";
export const SHOW_LOADING_VIDEOGALLERY_LIST = "SHOW_LOADING_VIDEOGALLERY_LIST";

export const VIDEOGALLERY_DELETE = "VIDEOGALLERY_DELETE";
export const VIDEOGALLERY_DELETE_SUCCESS = "VIDEOGALLERY_DELETE_SUCCESS";
export const VIDEOGALLERY_DELETE_FAILURE = "VIDEOGALLERY_DELETE_FAILURE";
export const SHOW_LOADING_VIDEOGALLERY_DELETE = "SHOW_LOADING_VIDEOGALLERY_DELETE";

